INSERT INTO noteful_notes (note_name, folder_id, content)
VALUES
    ('Dogs','1','Ipsum dolore reiciendis. Quae aut ex. Eaque reiciendis voluptates. Quaerat tempora et quia veritatis. Necessitatibus enim laboriosam corrupti necessitatibus nihil molestiae.\n \rExcepturi ullam ipsum itaque sed nulla qui. Laborum earum porro. Repellat maiores hic voluptatem. Distinctio nobis rerum fugit quae explicabo aliquam. Voluptatum aliquam aut rerum suscipit autem neque repellendus.\n \rAdipisci voluptas eaque odio. Eius et aliquam explicabo unde labore ratione fuga. Fugit reiciendis consectetur aliquid sint.'
    ),
    ('Cats','2','Accusantium ut minima blanditiis voluptatem iste sit necessitatibus necessitatibus. Ut provident beatae alias. Maxime commodi et in. Voluptas esse nobis unde est repellendus aut ipsum corrupti sunt. Minus aliquid eum soluta dolores sint aut alias dolores. Tempore quia et quia enim ratione dolore dolor.\n \rAmet occaecati repellendus sed odit. Nisi corporis autem eaque aut eum velit ut. Ad odit ex doloremque aliquam consequatur ut sint.\n \rId odit architecto. Minus dolore ullam. Occaecati nihil rerum sed non nostrum dignissimos perferendis velit veritatis.'
    ),
    ('Pigs','1','Corporis doloribus deleniti nam. Quidem fugit provident non unde ex. Aspernatur odio quibusdam laborum inventore voluptatibus. Voluptatum dignissimos ipsam qui consequatur ad dicta exercitationem vitae autem. Mollitia dolores in.\n \rLibero ad consequuntur quod omnis. Praesentium officiis nam eaque nihil nihil voluptatem harum est. Impedit atque in cupiditate non minima. Sint temporibus autem quidem expedita et nisi dolore et. Quo provident inventore ducimus quibusdam voluptatem fuga.\n \rSequi porro dolorem et illum quia est. Error voluptas quis voluptatem enim qui beatae. Ea vitae eligendi repellendus soluta fugit totam nulla voluptates dolorum. Neque repellat vel mollitia est placeat doloremque rem omnis. Dolores esse aut veritatis qui.'
    ),
    ('Birds','2','Consectetur consequatur architecto odit recusandae ducimus. Quidem sint eligendi quam et et aliquid. Magni exercitationem minus eos voluptas. Aut autem enim dolores vel officia aperiam in rerum. Et nobis in est rerum ipsam qui aut ea.\n \rRepudiandae in eveniet deserunt autem. Deserunt et sunt. Esse odit ea velit et possimus. Rerum harum non autem qui dolorem voluptatem. Sunt iste provident exercitationem rerum architecto minima. Ut nemo est.\n \rOfficiis nobis sed voluptatem quia. Reiciendis officia adipisci. Occaecati fuga dolores odit ut nesciunt corporis voluptatibus eos earum.'
    ),
    ('Bears','3','Repellendus sequi necessitatibus eius. Cum in iusto laborum et dolorem qui voluptate ullam. Dolores perferendis in. Sunt accusamus officiis voluptatem adipisci similique repudiandae quisquam provident quod.\n \rEst labore at doloribus. Unde corrupti libero reiciendis fugit. Eum similique sunt illo iusto.\n \rRecusandae iste sint sit omnis. Hic enim ducimus sed quod sequi quia cum rerum. Et excepturi numquam. Velit repellat mollitia ipsam placeat molestiae et. Qui qui et. Delectus nobis ex amet velit eos tenetur.'),
    ('Horses','3','Labore commodi ratione sed. Rerum et omnis qui ipsum libero. Quas sit autem velit reprehenderit non voluptatibus. Qui autem ea deleniti ipsam rerum ab vitae quaerat.\n \rEt placeat eius est qui. Dolores officia dolore accusantium et enim possimus. Velit voluptatem non dolor at consectetur ut accusantium rerum.\n \rRepudiandae reiciendis a fugiat deserunt voluptates. Non dignissimos tenetur ad. Harum veritatis harum vel. Blanditiis magnam animi minima iste asperiores.'),
    ('Tigers','1','Consectetur animi nobis. Illum laboriosam quam. Adipisci voluptas placeat dicta. Deleniti et et at sit qui deleniti iste repellat.\n \rNumquam aliquam laborum reprehenderit. Et quo mollitia praesentium suscipit fugiat dolorum. Atque quisquam sed est omnis consequuntur occaecati. Rerum iste quos ex.\n \rDignissimos quia voluptatem enim voluptatem asperiores facilis voluptatem molestiae. At iure dolor in rerum aliquid ratione voluptatem architecto laboriosam. Sit consequatur fugiat sint ex odit aperiam dolore dolorem. Voluptate corrupti fugiat quidem natus quibusdam error est. Quibusdam repudiandae perspiciatis impedit.'
    ),
    ('Wolves','2','Fuga id fugit at rerum dolorum doloribus qui animi. Eos occaecati rerum accusamus. Laudantium quam facilis quis magnam cupiditate porro illum. Quis modi sunt sed nihil in. Commodi reprehenderit similique fugit itaque repellendus eaque vel eos.\n \rVoluptates vitae et officia nihil quam et quia. Numquam quasi sint est vel est et. Sed eos aperiam autem omnis nihil ipsa a. Sapiente error voluptatem a aut et distinctio sit id.\n \rExplicabo beatae delectus molestiae. Et architecto blanditiis id quae magni laudantium dolores. Praesentium ad quo fuga dolores quod eaque. Non a quis architecto velit. Nobis voluptatem quis exercitationem aut dicta molestias voluptates.'
    ),
    ('Elephants','1','Rerum quia nam temporibus aut eos voluptatum autem vero non. Tempora nulla rerum animi aut voluptatibus eveniet vero excepturi rerum. Dolorum consequuntur et quis eveniet et vitae optio eum. Vero minima aliquid officia et id.\n \rRepudiandae sit id et consequatur. Architecto voluptas quasi sed aliquam. Dolorem ut quisquam esse velit et soluta provident. Neque ea consequatur id. Dolor earum nulla ut sint officiis est.\n \rIste quibusdam est nesciunt numquam voluptates. Dolorum vitae vel sint doloribus sit necessitatibus quo. Ipsa modi autem molestiae veritatis quis inventore. Vel temporibus eligendi dolores consectetur.'
    ),
    ('Lions','3','Quibusdam dicta iste. Quae quia ut sint sit nam. Quo itaque doloribus deserunt tenetur ut. Rerum dolor blanditiis enim voluptate ipsum explicabo.\n \rOptio distinctio vel mollitia tenetur. Quo assumenda tenetur laudantium iusto. Tempora quo voluptatibus quod rerum error voluptatem.\n \rQuis libero voluptas facilis et saepe debitis. Et voluptatem recusandae qui qui ipsam reiciendis labore nemo autem. Aut vero repellat possimus vel reprehenderit.'
    ),
    ('Monkeys','2','Harum ut tempora ullam vitae et provident rerum harum eos. Voluptatem impedit ea qui voluptas ut. Ut voluptates necessitatibus in nam atque nam magnam iure.\n \rTempore eveniet fugit nulla officiis dicta nihil ut beatae facilis. A magni sed veniam. Distinctio et sed excepturi.\n \rBeatae corporis aut. Asperiores sint fuga ad reiciendis. Aut voluptatem voluptatem.'
    ),
    ('Bats','3','Odio itaque placeat fugiat consequatur earum. Ea molestiae neque et delectus accusantium illo quis possimus cupiditate. Dolor qui temporibus aut aut omnis dicta nobis. Voluptatem quia ea doloremque doloremque magni ut culpa. Quasi consequatur earum unde. Quibusdam in hic tempora rem dolorem quo iste.\n \rDolores qui aperiam est quo. Porro distinctio ut eum sit rem autem enim est. Quae voluptatum earum et ipsam sed eius et.\n \rReiciendis quis unde. Dicta eum adipisci culpa sunt exercitationem. Odit qui et labore rem aut officia.'
    ),
    ('Turtles','2','Quis dolorum dolores. Sequi magnam occaecati natus dolore occaecati eos qui dolor commodi. Ullam quia quasi perspiciatis placeat ut voluptate velit dolores neque. Provident id facilis incidunt asperiores nesciunt molestias natus non saepe.\n \rIure nam voluptas quam. Ut adipisci rem est in quas aliquam. Voluptas ut ea. Amet sed et rerum quaerat. Quam debitis ea aut officiis dignissimos ipsam assumenda impedit. Cumque at et est provident.\n \rOmnis vero deserunt modi officiis ut consequatur veritatis dicta rerum. Ut enim nostrum aspernatur nihil quo quod recusandae recusandae occaecati. Molestias et rem. Fuga dolor exercitationem illum quasi recusandae reiciendis debitis expedita ipsum.'
    ),
    ('Zebras','3','Velit sit et debitis laudantium aut libero. Nisi perferendis alias nihil dolor. Rerum harum voluptatem aliquam nisi illo excepturi aliquam consequatur.\n \rSed in pariatur nisi aut fugiat. Praesentium hic atque consequuntur. Et ratione debitis deserunt. Quibusdam quia sint consectetur minima quas dolorem repudiandae.\n \rEst sapiente hic magnam laborum possimus. Atque adipisci in similique sed nulla necessitatibus aut sed. Laboriosam sunt est numquam omnis eaque.'
    );